---
title: "Project II ST558"
author: "Pratap Adhikari"
date: "10/9/2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message = F, warning = F, cache = T)
library(tidyverse)
library(haven)
library(knitr)
library(class)
library(caret)
library(tree)
library(gbm)
```

Read the data
```{r}
popData<- read_csv("OnlineNewsPopularity.csv")
head(popData)

```


```{r}
#day<- function(day, ...){}

```


### Processing

```{r}
# checking if any missing values in the raw data
anyNA(popData)
#summary(popData)
```
FALSE indicates there are no missing values. Next, to split the train and test set




```{r}  
# Create train and test data set.
set.seed(2)
train<- sample(1:nrow(popData), size = nrow(popData) *0.7)
test<- dplyr::setdiff(1:nrow(popData), train)

popDataTrain<- popData[train, -1]
popDataTest<- popData[test,-1]
```


```{r}
#difine all of  the days variables on data set
weekday<- c("weekday_is_monday", "weekday_is_tuesday", "weekday_is_wednesday", "weekday_is_thursday", "weekday_is_friday", "weekday_is_saturday", "weekday_is_sunday", "is_weekend" )
#create final train data set
popDataFinalTrain<- popDataTrain  %>% mutate(weekday= popDataTrain$weekday_is_monday) %>% select( -all_of(weekday), -is_weekend )

#create final test data set
popDataFinalTest<- popDataTest  %>% mutate(weekday= popDataTest$weekday_is_monday) %>% select( -all_of(weekday), -is_weekend )

```


# Tree Based model
```{r}
popTreeFit<- tree(shares~ ., data=popDataFinalTrain,
                  control= tree.control(nrow(popDataFinalTrain), mincut = 10, minsize = 20, mindev = 0.01))

plot(popTreeFit); text(popTreeFit)
summary(popTreeFit)
```




```{r eval=F}
#Using selected predictors only
#popDataFinalTrain$weekday<- as.factor(popDataFinalTrain$weekday)
popTreeFit1<- tree(shares~ kw_avg_avg + self_reference_min_shares + weekday ,
                  data=popDataFinalTrain)
plot(popTreeFit1); text(popTreeFit)
summary(popTreeFit1)
```


```{r}
#CV error
cvTree<- cv.tree(popTreeFit)
cvTree

```


Plot of CV error change
```{r}
plot(cvTree$size, cvTree$dev, type="b")

```

### Prediction

```{r}
predpop<- predict(popTreeFit, newdata= dplyr::select(popDataFinalTest, -shares) )

#RMSE
treeRMSE<- sqrt(mean(predpop - popDataFinalTest$shares)^2)
```







###########################################################

# Boosted Tree method:

```{r}
boostFit<- gbm(shares~ ., data=popDataFinalTrain, distribution = "gaussian", n.trees = 5000, shrinkage = 0.1, interaction.depth = 4)

boostPred<- predict(boostFit, newdata= dplyr::select(popDataFinalTest, -shares), n.trees=5000)

```

compare RMSE values (root of test prediction error)
```{r}
boostRMSE<- sqrt(mean(boostPred-popDataFinalTest$shares)^2 )

#table the RMSE from both of the model fits
kable (c(boost=boostRMSE, tree= treeRMSE))
```





#############################################################
# Using rpart function

```{r eval=F}

rpartFit<- rpart(shares~., data=popDataFinalTrain, 
      control= rpart.control( cp=0.01, minsplit = 6, 
              maxcompete = 4, maxsurrogate = 5, usesurrogate = 2, xval = 10,
              surrogatestyle = 0, maxdepth = 30 ) )


plot(rpartFit); text(rpartFit, pretty = 1, cex=0.8)
#summary(rpartFit)
```


```{r eval=F}

rpartFit<- rpart(shares~., data=popDataFinalTrain, 
      control= rpart.control( cp=0.01, minsplit = 6, minbucket = round(minsplit/3),
              maxcompete = 4, maxsurrogate = 5, usesurrogate = 2, xval = 10,
              surrogatestyle = 0, maxdepth = 30 ) )


plot(rpartFit); text(rpartFit, pretty = 1, cex=0.8)
#summary(rpartFit)
```

```{r eval=F}

rpart(shares~., data=popDataFinalTrain, 
      control= rpart.control(minsplit = 3, minbucket = round(minsplit/3), cp=0.01, 
              maxcompete = 4, maxsurrogate = 5, usesurrogate = 2, xval = 10,
              surrogatestyle = 0, maxdepth = 30 ) )

```


#################################################################

